#DISTFILES += \
OTHER_FILES += \
    $$PWD/qml-extras/modules/Material/Extras/images/circle.png \
    $$PWD/qml-extras/modules/Material/Extras/js/dateutils.js \
    $$PWD/qml-extras/modules/Material/Extras/js/httplib.js \
    $$PWD/qml-extras/modules/Material/Extras/js/listutils.js \
    $$PWD/qml-extras/modules/Material/Extras/js/promises.js \
    $$PWD/qml-extras/modules/Material/Extras/js/utils.js \
    $$PWD/qml-extras/modules/Material/Extras/AutomaticGrid.qml \
    $$PWD/qml-extras/modules/Material/Extras/CircleImage.qml \
    $$PWD/qml-extras/modules/Material/Extras/CircleMask.qml \
    $$PWD/qml-extras/modules/Material/Extras/ColumnFlow.qml \
    $$PWD/qml-extras/modules/Material/Extras/Document.qml \
    $$PWD/qml-extras/modules/Material/Extras/Image.qml \
    $$PWD/qml-extras/modules/Material/Extras/Object.qml \
    $$PWD/qml-extras/modules/Material/Extras/qmldir \
    $$PWD/qml-material/modules/Material/Slider.qml \
    $$PWD/qml-material/modules/Material/Ink.qml \
    $$PWD/qml-material/modules/Material/Palette.qml \
    $$PWD/qml-material/modules/Material/RadioButton.qml \
    $$PWD/qml-material/modules/Material/ProgressCircle.qml \
    $$PWD/qml-material/modules/Material/Tooltip.qml \
    $$PWD/qml-material/modules/Material/Theme.qml \
    $$PWD/qml-material/modules/Material/ListItems \
    $$PWD/qml-material/modules/Material/ListItems/BaseListItem.qml \
    $$PWD/qml-material/modules/Material/ListItems/qmldir \
    $$PWD/qml-material/modules/Material/ListItems/Subtitled.qml \
    $$PWD/qml-material/modules/Material/ListItems/Standard.qml \
    $$PWD/qml-material/modules/Material/ListItems/SimpleMenu.qml \
    $$PWD/qml-material/modules/Material/ListItems/Header.qml \
    $$PWD/qml-material/modules/Material/Scrollbar.qml \
    $$PWD/qml-material/modules/Material/Page.qml \
    $$PWD/qml-material/modules/Material/Snackbar.qml \
    $$PWD/qml-material/modules/Material/MainView.qml \
    $$PWD/qml-material/modules/Material/Material.pro \
    $$PWD/qml-material/modules/Material/Device.qml \
    $$PWD/qml-material/modules/Material/qmldir \
    $$PWD/qml-material/modules/Material/PopupBase.qml \
    $$PWD/qml-material/modules/Material/ThinDivider.qml \
    $$PWD/qml-material/modules/Material/OverlayView.qml \
    $$PWD/qml-material/modules/Material/Sidebar.qml \
    $$PWD/qml-material/modules/Material/ApplicationWindow.qml \
    $$PWD/qml-material/modules/Material/Action.qml \
    $$PWD/qml-material/modules/Material/PageSidebar.qml \
    $$PWD/qml-material/modules/Material/PageStack.qml \
    $$PWD/qml-material/modules/Material/Icon.qml \
    $$PWD/qml-material/modules/Material/Button.qml \
    $$PWD/qml-material/modules/Material/ProgressBar.qml \
    $$PWD/qml-material/modules/Material/fonts/roboto \
    $$PWD/qml-material/modules/Material/fonts/roboto/Roboto-BoldItalic.ttf \
    $$PWD/qml-material/modules/Material/fonts/roboto/RobotoCondensed-Bold.ttf \
    $$PWD/qml-material/modules/Material/fonts/roboto/RobotoCondensed-LightItalic.ttf \
    $$PWD/qml-material/modules/Material/fonts/roboto/Roboto-ThinItalic.ttf \
    $$PWD/qml-material/modules/Material/fonts/roboto/Roboto-BlackItalic.ttf \
    $$PWD/qml-material/modules/Material/fonts/roboto/Roboto-LightItalic.ttf \
    $$PWD/qml-material/modules/Material/fonts/roboto/RobotoCondensed-Regular.ttf \
    $$PWD/qml-material/modules/Material/fonts/roboto/RobotoCondensed-Light.ttf \
    $$PWD/qml-material/modules/Material/fonts/roboto/Roboto-Italic.ttf \
    $$PWD/qml-material/modules/Material/fonts/roboto/Roboto-Regular.ttf \
    $$PWD/qml-material/modules/Material/fonts/roboto/Roboto-Thin.ttf \
    $$PWD/qml-material/modules/Material/fonts/roboto/Roboto-Bold.ttf \
    $$PWD/qml-material/modules/Material/fonts/roboto/RobotoCondensed-BoldItalic.ttf \
    $$PWD/qml-material/modules/Material/fonts/roboto/RobotoCondensed-Italic.ttf \
    $$PWD/qml-material/modules/Material/fonts/roboto/Roboto-MediumItalic.ttf \
    $$PWD/qml-material/modules/Material/fonts/roboto/Roboto-Black.ttf \
    $$PWD/qml-material/modules/Material/fonts/roboto/Roboto-Medium.ttf \
    $$PWD/qml-material/modules/Material/fonts/roboto/Roboto-Light.ttf \
    $$PWD/qml-material/modules/Material/fonts/fontawesome/FontAwesome.otf \
    $$PWD/qml-material/modules/Material/Wave.qml \
    $$PWD/qml-material/modules/Material/NavigationDrawer.qml \
    $$PWD/qml-material/modules/Material/ThemePalette.qml \
    $$PWD/qml-material/modules/Material/Tabs.qml \
    $$PWD/qml-material/modules/Material/TabView.qml \
    $$PWD/qml-material/modules/Material/View.qml \
    $$PWD/qml-material/modules/Material/Object.qml \
    $$PWD/qml-material/modules/Material/AwesomeIcon.qml \
    $$PWD/qml-material/modules/Material/CheckBox.qml \
    $$PWD/qml-material/modules/Material/ActionButton.qml \
    $$PWD/qml-material/modules/Material/OverlayLayer.qml \
    $$PWD/qml-material/modules/Material/MaterialAnimation.qml \
    $$PWD/qml-material/modules/Material/Dropdown.qml \
    $$PWD/qml-material/modules/Material/awesome.js \
    $$PWD/qml-material/modules/Material/Dialog.qml \
    $$PWD/qml-material/modules/Material/make_awesome.py \
    $$PWD/qml-material/modules/Material/Window.qml \
    $$PWD/qml-material/modules/Material/Toolbar.qml \
    $$PWD/qml-material/modules/Material/Switch.qml \
    $$PWD/qml-material/modules/Material/AppTheme.qml \
    $$PWD/qml-material/modules/Material/ActionBar.qml \
    $$PWD/qml-material/modules/Material/Card.qml \
    $$PWD/qml-material/modules/Material/MenuField.qml \
    $$PWD/qml-material/modules/Material/units.qml \
    $$PWD/qml-material/modules/Material/TextField.qml \
    $$PWD/qml-material/modules/Material/Label.qml \
    $$PWD/qml-material/modules/Material/icons/alert/error.svg \
    $$PWD/qml-material/modules/Material/icons/alert/warning.svg \
    $$PWD/qml-material/modules/Material/icons/editor/border_all.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_list_numbered.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_textdirection_l_to_r.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_color_fill.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_underline.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_size.svg \
    $$PWD/qml-material/modules/Material/icons/editor/insert_drive_file.svg \
    $$PWD/qml-material/modules/Material/icons/editor/mode_comment.svg \
    $$PWD/qml-material/modules/Material/icons/editor/insert_invitation.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_align_center.svg \
    $$PWD/qml-material/modules/Material/icons/editor/border_inner.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_align_justify.svg \
    $$PWD/qml-material/modules/Material/icons/editor/border_right.svg \
    $$PWD/qml-material/modules/Material/icons/editor/insert_photo.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_quote.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_italic.svg \
    $$PWD/qml-material/modules/Material/icons/editor/border_vertical.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_align_right.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_indent_decrease.svg \
    $$PWD/qml-material/modules/Material/icons/editor/attach_file.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_list_bulleted.svg \
    $$PWD/qml-material/modules/Material/icons/editor/vertical_align_top.svg \
    $$PWD/qml-material/modules/Material/icons/editor/vertical_align_center.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_indent_increase.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_textdirection_r_to_l.svg \
    $$PWD/qml-material/modules/Material/icons/editor/wrap_text.svg \
    $$PWD/qml-material/modules/Material/icons/editor/border_top.svg \
    $$PWD/qml-material/modules/Material/icons/editor/border_style.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_color_text.svg \
    $$PWD/qml-material/modules/Material/icons/editor/vertical_align_bottom.svg \
    $$PWD/qml-material/modules/Material/icons/editor/publish.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_paint.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_align_left.svg \
    $$PWD/qml-material/modules/Material/icons/editor/insert_chart.svg \
    $$PWD/qml-material/modules/Material/icons/editor/insert_link.svg \
    $$PWD/qml-material/modules/Material/icons/editor/mode_edit.svg \
    $$PWD/qml-material/modules/Material/icons/editor/border_color.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_bold.svg \
    $$PWD/qml-material/modules/Material/icons/editor/insert_comment.svg \
    $$PWD/qml-material/modules/Material/icons/editor/border_bottom.svg \
    $$PWD/qml-material/modules/Material/icons/editor/border_clear.svg \
    $$PWD/qml-material/modules/Material/icons/editor/merge_type.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_strikethrough.svg \
    $$PWD/qml-material/modules/Material/icons/editor/insert_emoticon.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_line_spacing.svg \
    $$PWD/qml-material/modules/Material/icons/editor/border_left.svg \
    $$PWD/qml-material/modules/Material/icons/editor/border_outer.svg \
    $$PWD/qml-material/modules/Material/icons/editor/attach_money.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_clear.svg \
    $$PWD/qml-material/modules/Material/icons/editor/format_color_reset.svg \
    $$PWD/qml-material/modules/Material/icons/editor/functions.svg \
    $$PWD/qml-material/modules/Material/icons/editor/border_horizontal.svg \
    $$PWD/qml-material/modules/Material/icons/file/file_download.svg \
    $$PWD/qml-material/modules/Material/icons/file/cloud_done.svg \
    $$PWD/qml-material/modules/Material/icons/file/cloud_upload.svg \
    $$PWD/qml-material/modules/Material/icons/file/folder_shared.svg \
    $$PWD/qml-material/modules/Material/icons/file/cloud_download.svg \
    $$PWD/qml-material/modules/Material/icons/file/cloud_queue.svg \
    $$PWD/qml-material/modules/Material/icons/file/file_upload.svg \
    $$PWD/qml-material/modules/Material/icons/file/cloud.svg \
    $$PWD/qml-material/modules/Material/icons/file/folder.svg \
    $$PWD/qml-material/modules/Material/icons/file/folder_open.svg \
    $$PWD/qml-material/modules/Material/icons/file/cloud_off.svg \
    $$PWD/qml-material/modules/Material/icons/file/cloud_circle.svg \
    $$PWD/qml-material/modules/Material/icons/file/attachment.svg \
    $$PWD/qml-material/modules/Material/icons/toggle/check_box.svg \
    $$PWD/qml-material/modules/Material/icons/toggle/star_half.svg \
    $$PWD/qml-material/modules/Material/icons/toggle/star_outline.svg \
    $$PWD/qml-material/modules/Material/icons/toggle/radio_button_off.svg \
    $$PWD/qml-material/modules/Material/icons/toggle/check_box_outline_blank.svg \
    $$PWD/qml-material/modules/Material/icons/toggle/radio_button_on.svg \
    $$PWD/qml-material/modules/Material/icons/toggle/star.svg \
    $$PWD/qml-material/modules/Material/icons/action/swap_horiz.svg \
    $$PWD/qml-material/modules/Material/icons/action/restore.svg \
    $$PWD/qml-material/modules/Material/icons/action/settings_remote.svg \
    $$PWD/qml-material/modules/Material/icons/action/perm_phone_msg.svg \
    $$PWD/qml-material/modules/Material/icons/action/speaker_notes.svg \
    $$PWD/qml-material/modules/Material/icons/action/list.svg \
    $$PWD/qml-material/modules/Material/icons/action/launch.svg \
    $$PWD/qml-material/modules/Material/icons/action/wallet_travel.svg \
    $$PWD/qml-material/modules/Material/icons/action/settings_cell.svg \
    $$PWD/qml-material/modules/Material/icons/action/query_builder.svg \
    $$PWD/qml-material/modules/Material/icons/action/polymer.svg \
    $$PWD/qml-material/modules/Material/icons/action/redeem.svg \
    $$PWD/qml-material/modules/Material/icons/action/grade.svg \
    $$PWD/qml-material/modules/Material/icons/action/translate.svg \
    $$PWD/qml-material/modules/Material/icons/action/view_day.svg \
    $$PWD/qml-material/modules/Material/icons/action/question_answer.svg \
    $$PWD/qml-material/modules/Material/icons/action/turned_in.svg \
    $$PWD/qml-material/modules/Material/icons/action/settings_voice.svg \
    $$PWD/qml-material/modules/Material/icons/action/pageview.svg \
    $$PWD/qml-material/modules/Material/icons/action/open_with.svg \
    $$PWD/qml-material/modules/Material/icons/action/announcement.svg \
    $$PWD/qml-material/modules/Material/icons/action/find_replace.svg \
    $$PWD/qml-material/modules/Material/icons/action/alarm_add.svg \
    $$PWD/qml-material/modules/Material/icons/action/shopping_cart.svg \
    $$PWD/qml-material/modules/Material/icons/action/theaters.svg \
    $$PWD/qml-material/modules/Material/icons/action/done.svg \
    $$PWD/qml-material/modules/Material/icons/action/account_box.svg \
    $$PWD/qml-material/modules/Material/icons/action/assignment_return.svg \
    $$PWD/qml-material/modules/Material/icons/action/home.svg \
    $$PWD/qml-material/modules/Material/icons/action/done_all.svg \
    $$PWD/qml-material/modules/Material/icons/action/assignment_turned_in.svg \
    $$PWD/qml-material/modules/Material/icons/action/settings_input_svideo.svg \
    $$PWD/qml-material/modules/Material/icons/action/perm_camera_mic.svg \
    $$PWD/qml-material/modules/Material/icons/action/settings_phone.svg \
    $$PWD/qml-material/modules/Material/icons/action/shop_two.svg \
    $$PWD/qml-material/modules/Material/icons/action/settings_backup_restore.svg \
    $$PWD/qml-material/modules/Material/icons/action/exit_to_app.svg \
    $$PWD/qml-material/modules/Material/icons/action/settings_applications.svg \
    $$PWD/qml-material/modules/Material/icons/action/store.svg \
    $$PWD/qml-material/modules/Material/icons/action/bookmark_outline.svg \
    $$PWD/qml-material/modules/Material/icons/action/check_circle.svg \
    $$PWD/qml-material/modules/Material/icons/action/markunread_mailbox.svg \
    $$PWD/qml-material/modules/Material/icons/action/bookmark.svg \
    $$PWD/qml-material/modules/Material/icons/action/view_array.svg \
    $$PWD/qml-material/modules/Material/icons/action/open_in_browser.svg \
    $$PWD/qml-material/modules/Material/icons/action/wallet_membership.svg \
    $$PWD/qml-material/modules/Material/icons/action/invert_colors.svg \
    $$PWD/qml-material/modules/Material/icons/action/language.svg \
    $$PWD/qml-material/modules/Material/icons/action/print.svg \
    $$PWD/qml-material/modules/Material/icons/action/settings_overscan.svg \
    $$PWD/qml-material/modules/Material/icons/action/shop.svg \
    $$PWD/qml-material/modules/Material/icons/action/star_rate.svg \
    $$PWD/qml-material/modules/Material/icons/action/settings_power.svg \
    $$PWD/qml-material/modules/Material/icons/action/reorder.svg \
    $$PWD/qml-material/modules/Material/icons/action/settings.svg \
    $$PWD/qml-material/modules/Material/icons/action/track_changes.svg \
    $$PWD/qml-material/modules/Material/icons/action/lock.svg \
    $$PWD/qml-material/modules/Material/icons/action/note_add.svg \
    $$PWD/qml-material/modules/Material/icons/action/settings_ethernet.svg \
    $$PWD/qml-material/modules/Material/icons/action/history.svg \
    $$PWD/qml-material/modules/Material/icons/action/cached.svg \
    $$PWD/qml-material/modules/Material/icons/action/view_stream.svg \
    $$PWD/qml-material/modules/Material/icons/action/perm_media.svg \
    $$PWD/qml-material/modules/Material/icons/action/flip_to_back.svg \
    $$PWD/qml-material/modules/Material/icons/action/subject.svg \
    $$PWD/qml-material/modules/Material/icons/action/perm_contact_cal.svg \
    $$PWD/qml-material/modules/Material/icons/action/wallet_giftcard.svg \
    $$PWD/qml-material/modules/Material/icons/action/alarm_off.svg \
    $$PWD/qml-material/modules/Material/icons/action/loyalty.svg \
    $$PWD/qml-material/modules/Material/icons/action/view_list.svg \
    $$PWD/qml-material/modules/Material/icons/action/android.svg \
    $$PWD/qml-material/modules/Material/icons/action/aspect_ratio.svg \
    $$PWD/qml-material/modules/Material/icons/action/help.svg \
    $$PWD/qml-material/modules/Material/icons/action/label.svg \
    $$PWD/qml-material/modules/Material/icons/action/thumbs_up_down.svg \
    $$PWD/qml-material/modules/Material/icons/action/turned_in_not.svg \
    $$PWD/qml-material/modules/Material/icons/action/bug_report.svg \
    $$PWD/qml-material/modules/Material/icons/action/settings_input_hdmi.svg \
    $$PWD/qml-material/modules/Material/icons/action/work.svg \
    $$PWD/qml-material/modules/Material/icons/action/view_week.svg \
    $$PWD/qml-material/modules/Material/icons/action/find_in_page.svg \
    $$PWD/qml-material/modules/Material/icons/action/room.svg \
    $$PWD/qml-material/modules/Material/icons/action/flip_to_front.svg \
    $$PWD/qml-material/modules/Material/icons/action/dashboard.svg \
    $$PWD/qml-material/modules/Material/icons/action/visibility_off.svg \
    $$PWD/qml-material/modules/Material/icons/action/class.svg \
    $$PWD/qml-material/modules/Material/icons/action/extension.svg \
    $$PWD/qml-material/modules/Material/icons/action/description.svg \
    $$PWD/qml-material/modules/Material/icons/action/visibility.svg \
    $$PWD/qml-material/modules/Material/icons/action/thumb_up.svg \
    $$PWD/qml-material/modules/Material/icons/action/delete.svg \
    $$PWD/qml-material/modules/Material/icons/action/report_problem.svg \
    $$PWD/qml-material/modules/Material/icons/action/lock_open.svg \
    $$PWD/qml-material/modules/Material/icons/action/search.svg \
    $$PWD/qml-material/modules/Material/icons/action/alarm_on.svg \
    $$PWD/qml-material/modules/Material/icons/action/tab.svg \
    $$PWD/qml-material/modules/Material/icons/action/info.svg \
    $$PWD/qml-material/modules/Material/icons/action/face.svg \
    $$PWD/qml-material/modules/Material/icons/action/picture_in_picture.svg \
    $$PWD/qml-material/modules/Material/icons/action/credit_card.svg \
    $$PWD/qml-material/modules/Material/icons/action/book.svg \
    $$PWD/qml-material/modules/Material/icons/action/view_headline.svg \
    $$PWD/qml-material/modules/Material/icons/action/autorenew.svg \
    $$PWD/qml-material/modules/Material/icons/action/explore.svg \
    $$PWD/qml-material/modules/Material/icons/action/group_work.svg \
    $$PWD/qml-material/modules/Material/icons/action/trending_neutral.svg \
    $$PWD/qml-material/modules/Material/icons/action/stars.svg \
    $$PWD/qml-material/modules/Material/icons/action/system_update_tv.svg \
    $$PWD/qml-material/modules/Material/icons/action/favorite.svg \
    $$PWD/qml-material/modules/Material/icons/action/swap_vert.svg \
    $$PWD/qml-material/modules/Material/icons/action/settings_bluetooth.svg \
    $$PWD/qml-material/modules/Material/icons/action/backup.svg \
    $$PWD/qml-material/modules/Material/icons/action/assignment_returned.svg \
    $$PWD/qml-material/modules/Material/icons/action/view_column.svg \
    $$PWD/qml-material/modules/Material/icons/action/receipt.svg \
    $$PWD/qml-material/modules/Material/icons/action/get_app.svg \
    $$PWD/qml-material/modules/Material/icons/action/3d_rotation.svg \
    $$PWD/qml-material/modules/Material/icons/action/event.svg \
    $$PWD/qml-material/modules/Material/icons/action/schedule.svg \
    $$PWD/qml-material/modules/Material/icons/action/settings_input_antenna.svg \
    $$PWD/qml-material/modules/Material/icons/action/view_module.svg \
    $$PWD/qml-material/modules/Material/icons/action/accessibility.svg \
    $$PWD/qml-material/modules/Material/icons/action/assignment_late.svg \
    $$PWD/qml-material/modules/Material/icons/action/supervisor_account.svg \
    $$PWD/qml-material/modules/Material/icons/action/highlight_remove.svg \
    $$PWD/qml-material/modules/Material/icons/action/verified_user.svg \
    $$PWD/qml-material/modules/Material/icons/action/swap_vert_circle.svg \
    $$PWD/qml-material/modules/Material/icons/action/alarm.svg \
    $$PWD/qml-material/modules/Material/icons/action/view_quilt.svg \
    $$PWD/qml-material/modules/Material/icons/action/open_in_new.svg \
    $$PWD/qml-material/modules/Material/icons/action/toc.svg \
    $$PWD/qml-material/modules/Material/icons/action/assignment_ind.svg \
    $$PWD/qml-material/modules/Material/icons/action/account_child.svg \
    $$PWD/qml-material/modules/Material/icons/action/payment.svg \
    $$PWD/qml-material/modules/Material/icons/action/label_outline.svg \
    $$PWD/qml-material/modules/Material/icons/action/trending_down.svg \
    $$PWD/qml-material/modules/Material/icons/action/perm_scan_wifi.svg \
    $$PWD/qml-material/modules/Material/icons/action/https.svg \
    $$PWD/qml-material/modules/Material/icons/action/add_shopping_cart.svg \
    $$PWD/qml-material/modules/Material/icons/action/tab_unselected.svg \
    $$PWD/qml-material/modules/Material/icons/action/account_balance.svg \
    $$PWD/qml-material/modules/Material/icons/action/view_agenda.svg \
    $$PWD/qml-material/modules/Material/icons/action/today.svg \
    $$PWD/qml-material/modules/Material/icons/action/assessment.svg \
    $$PWD/qml-material/modules/Material/icons/action/perm_data_setting.svg \
    $$PWD/qml-material/modules/Material/icons/action/settings_input_component.svg \
    $$PWD/qml-material/modules/Material/icons/action/account_circle.svg \
    $$PWD/qml-material/modules/Material/icons/action/lock_outline.svg \
    $$PWD/qml-material/modules/Material/icons/action/shopping_basket.svg \
    $$PWD/qml-material/modules/Material/icons/action/assignment.svg \
    $$PWD/qml-material/modules/Material/icons/action/dns.svg \
    $$PWD/qml-material/modules/Material/icons/action/settings_display.svg \
    $$PWD/qml-material/modules/Material/icons/action/trending_up.svg \
    $$PWD/qml-material/modules/Material/icons/action/account_balance_wallet.svg \
    $$PWD/qml-material/modules/Material/icons/action/view_carousel.svg \
    $$PWD/qml-material/modules/Material/icons/action/perm_identity.svg \
    $$PWD/qml-material/modules/Material/icons/action/spellcheck.svg \
    $$PWD/qml-material/modules/Material/icons/action/favorite_outline.svg \
    $$PWD/qml-material/modules/Material/icons/action/info_outline.svg \
    $$PWD/qml-material/modules/Material/icons/action/perm_device_info.svg \
    $$PWD/qml-material/modules/Material/icons/action/settings_input_composite.svg \
    $$PWD/qml-material/modules/Material/icons/action/input.svg \
    $$PWD/qml-material/modules/Material/icons/action/thumb_down.svg \
    $$PWD/qml-material/modules/Material/icons/notification/phone_paused.svg \
    $$PWD/qml-material/modules/Material/icons/notification/play_install.svg \
    $$PWD/qml-material/modules/Material/icons/notification/sync_disabled.svg \
    $$PWD/qml-material/modules/Material/icons/notification/do_not_disturb.svg \
    $$PWD/qml-material/modules/Material/icons/notification/phone_forwarded.svg \
    $$PWD/qml-material/modules/Material/icons/notification/more.svg \
    $$PWD/qml-material/modules/Material/icons/notification/play_download.svg \
    $$PWD/qml-material/modules/Material/icons/notification/system_update.svg \
    $$PWD/qml-material/modules/Material/icons/notification/dnd_forwardslash.svg \
    $$PWD/qml-material/modules/Material/icons/notification/event_note.svg \
    $$PWD/qml-material/modules/Material/icons/notification/folder_special.svg \
    $$PWD/qml-material/modules/Material/icons/notification/voice_chat.svg \
    $$PWD/qml-material/modules/Material/icons/notification/sim_card_alert.svg \
    $$PWD/qml-material/modules/Material/icons/notification/sync.svg \
    $$PWD/qml-material/modules/Material/icons/notification/mms.svg \
    $$PWD/qml-material/modules/Material/icons/notification/tap_and_play.svg \
    $$PWD/qml-material/modules/Material/icons/notification/adb.svg \
    $$PWD/qml-material/modules/Material/icons/notification/bluetooth_audio.svg \
    $$PWD/qml-material/modules/Material/icons/notification/disc_full.svg \
    $$PWD/qml-material/modules/Material/icons/notification/sync_problem.svg \
    $$PWD/qml-material/modules/Material/icons/notification/drive_eta.svg \
    $$PWD/qml-material/modules/Material/icons/notification/vpn_lock.svg \
    $$PWD/qml-material/modules/Material/icons/notification/sms.svg \
    $$PWD/qml-material/modules/Material/icons/notification/time_to_leave.svg \
    $$PWD/qml-material/modules/Material/icons/notification/sms_failed.svg \
    $$PWD/qml-material/modules/Material/icons/notification/network_locked.svg \
    $$PWD/qml-material/modules/Material/icons/notification/vibration.svg \
    $$PWD/qml-material/modules/Material/icons/notification/phone_missed.svg \
    $$PWD/qml-material/modules/Material/icons/notification/event_available.svg \
    $$PWD/qml-material/modules/Material/icons/notification/event_busy.svg \
    $$PWD/qml-material/modules/Material/icons/notification/phone_in_talk.svg \
    $$PWD/qml-material/modules/Material/icons/notification/sd_card.svg \
    $$PWD/qml-material/modules/Material/icons/notification/phone_locked.svg \
    $$PWD/qml-material/modules/Material/icons/notification/phone_bluetooth_speaker.svg \
    $$PWD/qml-material/modules/Material/icons/image/panorama_horizontal.svg \
    $$PWD/qml-material/modules/Material/icons/image/camera_front.svg \
    $$PWD/qml-material/modules/Material/icons/image/timer.svg \
    $$PWD/qml-material/modules/Material/icons/image/brightness_2.svg \
    $$PWD/qml-material/modules/Material/icons/image/photo_library.svg \
    $$PWD/qml-material/modules/Material/icons/image/panorama_wide_angle.svg \
    $$PWD/qml-material/modules/Material/icons/image/filter_none.svg \
    $$PWD/qml-material/modules/Material/icons/image/crop_free.svg \
    $$PWD/qml-material/modules/Material/icons/image/photo_camera.svg \
    $$PWD/qml-material/modules/Material/icons/image/flare.svg \
    $$PWD/qml-material/modules/Material/icons/image/filter_1.svg \
    $$PWD/qml-material/modules/Material/icons/image/looks_5.svg \
    $$PWD/qml-material/modules/Material/icons/image/portrait.svg \
    $$PWD/qml-material/modules/Material/icons/image/blur_linear.svg \
    $$PWD/qml-material/modules/Material/icons/image/looks_two.svg \
    $$PWD/qml-material/modules/Material/icons/image/panorama_fisheye.svg \
    $$PWD/qml-material/modules/Material/icons/image/exposure_minus_1.svg \
    $$PWD/qml-material/modules/Material/icons/image/slideshow.svg \
    $$PWD/qml-material/modules/Material/icons/image/exposure_plus_1.svg \
    $$PWD/qml-material/modules/Material/icons/image/movie_creation.svg \
    $$PWD/qml-material/modules/Material/icons/image/crop_7_5.svg \
    $$PWD/qml-material/modules/Material/icons/image/hdr_off.svg \
    $$PWD/qml-material/modules/Material/icons/image/brightness_6.svg \
    $$PWD/qml-material/modules/Material/icons/image/details.svg \
    $$PWD/qml-material/modules/Material/icons/image/wb_auto.svg \
    $$PWD/qml-material/modules/Material/icons/image/hdr_strong.svg \
    $$PWD/qml-material/modules/Material/icons/image/brightness_7.svg \
    $$PWD/qml-material/modules/Material/icons/image/transform.svg \
    $$PWD/qml-material/modules/Material/icons/image/flash_off.svg \
    $$PWD/qml-material/modules/Material/icons/image/crop_16_9.svg \
    $$PWD/qml-material/modules/Material/icons/image/hdr_weak.svg \
    $$PWD/qml-material/modules/Material/icons/image/filter_hdr.svg \
    $$PWD/qml-material/modules/Material/icons/image/gradient.svg \
    $$PWD/qml-material/modules/Material/icons/image/timer_3.svg \
    $$PWD/qml-material/modules/Material/icons/image/filter_8.svg \
    $$PWD/qml-material/modules/Material/icons/image/panorama_vertical.svg \
    $$PWD/qml-material/modules/Material/icons/image/flip.svg \
    $$PWD/qml-material/modules/Material/icons/image/timer_10.svg \
    $$PWD/qml-material/modules/Material/icons/image/adjust.svg \
    $$PWD/qml-material/modules/Material/icons/image/panorama.svg \
    $$PWD/qml-material/modules/Material/icons/image/rotate_left.svg \
    $$PWD/qml-material/modules/Material/icons/image/edit.svg \
    $$PWD/qml-material/modules/Material/icons/image/brightness_4.svg \
    $$PWD/qml-material/modules/Material/icons/image/exposure_plus_2.svg \
    $$PWD/qml-material/modules/Material/icons/image/brush.svg \
    $$PWD/qml-material/modules/Material/icons/image/nature.svg \
    $$PWD/qml-material/modules/Material/icons/image/looks_4.svg \
    $$PWD/qml-material/modules/Material/icons/image/brightness_5.svg \
    $$PWD/qml-material/modules/Material/icons/image/crop_original.svg \
    $$PWD/qml-material/modules/Material/icons/image/leak_remove.svg \
    $$PWD/qml-material/modules/Material/icons/image/filter_2.svg \
    $$PWD/qml-material/modules/Material/icons/image/iso.svg \
    $$PWD/qml-material/modules/Material/icons/image/exposure.svg \
    $$PWD/qml-material/modules/Material/icons/image/center_focus_strong.svg \
    $$PWD/qml-material/modules/Material/icons/image/wb_cloudy.svg \
    $$PWD/qml-material/modules/Material/icons/image/crop_square.svg \
    $$PWD/qml-material/modules/Material/icons/image/image.svg \
    $$PWD/qml-material/modules/Material/icons/image/color_lens.svg \
    $$PWD/qml-material/modules/Material/icons/image/lens.svg \
    $$PWD/qml-material/modules/Material/icons/image/grid_on.svg \
    $$PWD/qml-material/modules/Material/icons/image/healing.svg \
    $$PWD/qml-material/modules/Material/icons/image/camera_roll.svg \
    $$PWD/qml-material/modules/Material/icons/image/center_focus_weak.svg \
    $$PWD/qml-material/modules/Material/icons/image/filter_5.svg \
    $$PWD/qml-material/modules/Material/icons/image/wb_sunny.svg \
    $$PWD/qml-material/modules/Material/icons/image/camera.svg \
    $$PWD/qml-material/modules/Material/icons/image/filter_9_plus.svg \
    $$PWD/qml-material/modules/Material/icons/image/navigate_next.svg \
    $$PWD/qml-material/modules/Material/icons/image/filter_6.svg \
    $$PWD/qml-material/modules/Material/icons/image/palette.svg \
    $$PWD/qml-material/modules/Material/icons/image/crop_din.svg \
    $$PWD/qml-material/modules/Material/icons/image/camera_rear.svg \
    $$PWD/qml-material/modules/Material/icons/image/image_aspect_ratio.svg \
    $$PWD/qml-material/modules/Material/icons/image/control_point_duplicate.svg \
    $$PWD/qml-material/modules/Material/icons/image/compare.svg \
    $$PWD/qml-material/modules/Material/icons/image/filter_vintage.svg \
    $$PWD/qml-material/modules/Material/icons/image/crop.svg \
    $$PWD/qml-material/modules/Material/icons/image/timelapse.svg \
    $$PWD/qml-material/modules/Material/icons/image/crop_portrait.svg \
    $$PWD/qml-material/modules/Material/icons/image/wb_irradescent.svg \
    $$PWD/qml-material/modules/Material/icons/image/filter_drama.svg \
    $$PWD/qml-material/modules/Material/icons/image/grid_off.svg \
    $$PWD/qml-material/modules/Material/icons/image/style.svg \
    $$PWD/qml-material/modules/Material/icons/image/filter.svg \
    $$PWD/qml-material/modules/Material/icons/image/filter_b_and_w.svg \
    $$PWD/qml-material/modules/Material/icons/image/audiotrack.svg \
    $$PWD/qml-material/modules/Material/icons/image/leak_add.svg \
    $$PWD/qml-material/modules/Material/icons/image/filter_9.svg \
    $$PWD/qml-material/modules/Material/icons/image/remove_red_eye.svg \
    $$PWD/qml-material/modules/Material/icons/image/straighten.svg \
    $$PWD/qml-material/modules/Material/icons/image/dehaze.svg \
    $$PWD/qml-material/modules/Material/icons/image/loupe.svg \
    $$PWD/qml-material/modules/Material/icons/image/flash_on.svg \
    $$PWD/qml-material/modules/Material/icons/image/switch_video.svg \
    $$PWD/qml-material/modules/Material/icons/image/brightness_3.svg \
    $$PWD/qml-material/modules/Material/icons/image/crop_landscape.svg \
    $$PWD/qml-material/modules/Material/icons/image/assistant_photo.svg \
    $$PWD/qml-material/modules/Material/icons/image/texture.svg \
    $$PWD/qml-material/modules/Material/icons/image/blur_on.svg \
    $$PWD/qml-material/modules/Material/icons/image/crop_3_2.svg \
    $$PWD/qml-material/modules/Material/icons/image/tonality.svg \
    $$PWD/qml-material/modules/Material/icons/image/tag_faces.svg \
    $$PWD/qml-material/modules/Material/icons/image/camera_alt.svg \
    $$PWD/qml-material/modules/Material/icons/image/filter_frames.svg \
    $$PWD/qml-material/modules/Material/icons/image/wb_incandescent.svg \
    $$PWD/qml-material/modules/Material/icons/image/photo_album.svg \
    $$PWD/qml-material/modules/Material/icons/image/looks.svg \
    $$PWD/qml-material/modules/Material/icons/image/control_point.svg \
    $$PWD/qml-material/modules/Material/icons/image/looks_6.svg \
    $$PWD/qml-material/modules/Material/icons/image/add_to_photos.svg \
    $$PWD/qml-material/modules/Material/icons/image/exposure_minus_2.svg \
    $$PWD/qml-material/modules/Material/icons/image/switch_camera.svg \
    $$PWD/qml-material/modules/Material/icons/image/rotate_right.svg \
    $$PWD/qml-material/modules/Material/icons/image/crop_5_4.svg \
    $$PWD/qml-material/modules/Material/icons/image/tune.svg \
    $$PWD/qml-material/modules/Material/icons/image/brightness_1.svg \
    $$PWD/qml-material/modules/Material/icons/image/hdr_on.svg \
    $$PWD/qml-material/modules/Material/icons/image/navigate_before.svg \
    $$PWD/qml-material/modules/Material/icons/image/collections.svg \
    $$PWD/qml-material/modules/Material/icons/image/filter_center_focus.svg \
    $$PWD/qml-material/modules/Material/icons/image/grain.svg \
    $$PWD/qml-material/modules/Material/icons/image/timer_auto.svg \
    $$PWD/qml-material/modules/Material/icons/image/looks_one.svg \
    $$PWD/qml-material/modules/Material/icons/image/blur_circular.svg \
    $$PWD/qml-material/modules/Material/icons/image/flash_auto.svg \
    $$PWD/qml-material/modules/Material/icons/image/landscape.svg \
    $$PWD/qml-material/modules/Material/icons/image/timer_off.svg \
    $$PWD/qml-material/modules/Material/icons/image/photo.svg \
    $$PWD/qml-material/modules/Material/icons/image/filter_3.svg \
    $$PWD/qml-material/modules/Material/icons/image/colorize.svg \
    $$PWD/qml-material/modules/Material/icons/image/looks_3.svg \
    $$PWD/qml-material/modules/Material/icons/image/filter_tilt_shift.svg \
    $$PWD/qml-material/modules/Material/icons/image/filter_4.svg \
    $$PWD/qml-material/modules/Material/icons/image/exposure_zero.svg \
    $$PWD/qml-material/modules/Material/icons/image/nature_people.svg \
    $$PWD/qml-material/modules/Material/icons/image/blur_off.svg \
    $$PWD/qml-material/modules/Material/icons/image/filter_7.svg \
    $$PWD/qml-material/modules/Material/icons/device/network_cell.svg \
    $$PWD/qml-material/modules/Material/icons/device/screen_rotation.svg \
    $$PWD/qml-material/modules/Material/icons/device/signal_cellular_connected_no_internet_1_bar.svg \
    $$PWD/qml-material/modules/Material/icons/device/battery_90.svg \
    $$PWD/qml-material/modules/Material/icons/device/network_wifi.svg \
    $$PWD/qml-material/modules/Material/icons/device/signal_cellular_3_bar.svg \
    $$PWD/qml-material/modules/Material/icons/device/signal_wifi_2_bar.svg \
    $$PWD/qml-material/modules/Material/icons/device/usb.svg \
    $$PWD/qml-material/modules/Material/icons/device/bluetooth_connected.svg \
    $$PWD/qml-material/modules/Material/icons/device/screen_lock_rotation.svg \
    $$PWD/qml-material/modules/Material/icons/device/signal_wifi_0_bar.svg \
    $$PWD/qml-material/modules/Material/icons/device/multitrack_audio.svg \
    $$PWD/qml-material/modules/Material/icons/device/wifi_lock.svg \
    $$PWD/qml-material/modules/Material/icons/device/now_widgets.svg \
    $$PWD/qml-material/modules/Material/icons/device/signal_cellular_connected_no_internet_0_bar.svg \
    $$PWD/qml-material/modules/Material/icons/device/brightness_high.svg \
    $$PWD/qml-material/modules/Material/icons/device/settings_system_daydream.svg \
    $$PWD/qml-material/modules/Material/icons/device/bluetooth.svg \
    $$PWD/qml-material/modules/Material/icons/device/signal_wifi_1_bar.svg \
    $$PWD/qml-material/modules/Material/icons/device/access_alarm.svg \
    $$PWD/qml-material/modules/Material/icons/device/battery_charging_30.svg \
    $$PWD/qml-material/modules/Material/icons/device/access_time.svg \
    $$PWD/qml-material/modules/Material/icons/device/gps_not_fixed.svg \
    $$PWD/qml-material/modules/Material/icons/device/battery_charging_80.svg \
    $$PWD/qml-material/modules/Material/icons/device/sd_storage.svg \
    $$PWD/qml-material/modules/Material/icons/device/signal_cellular_0_bar.svg \
    $$PWD/qml-material/modules/Material/icons/device/signal_cellular_no_sim.svg \
    $$PWD/qml-material/modules/Material/icons/device/signal_cellular_null.svg \
    $$PWD/qml-material/modules/Material/icons/device/signal_cellular_4_bar.svg \
    $$PWD/qml-material/modules/Material/icons/device/battery_charging_20.svg \
    $$PWD/qml-material/modules/Material/icons/device/bluetooth_searching.svg \
    $$PWD/qml-material/modules/Material/icons/device/now_wallpaper.svg \
    $$PWD/qml-material/modules/Material/icons/device/devices.svg \
    $$PWD/qml-material/modules/Material/icons/device/airplanemode_on.svg \
    $$PWD/qml-material/modules/Material/icons/device/battery_80.svg \
    $$PWD/qml-material/modules/Material/icons/device/battery_charging_full.svg \
    $$PWD/qml-material/modules/Material/icons/device/add_alarm.svg \
    $$PWD/qml-material/modules/Material/icons/device/battery_std.svg \
    $$PWD/qml-material/modules/Material/icons/device/location_disabled.svg \
    $$PWD/qml-material/modules/Material/icons/device/signal_cellular_connected_no_internet_3_bar.svg \
    $$PWD/qml-material/modules/Material/icons/device/storage.svg \
    $$PWD/qml-material/modules/Material/icons/device/airplanemode_off.svg \
    $$PWD/qml-material/modules/Material/icons/device/signal_cellular_1_bar.svg \
    $$PWD/qml-material/modules/Material/icons/device/signal_cellular_connected_no_internet_4_bar.svg \
    $$PWD/qml-material/modules/Material/icons/device/signal_cellular_2_bar.svg \
    $$PWD/qml-material/modules/Material/icons/device/brightness_low.svg \
    $$PWD/qml-material/modules/Material/icons/device/nfc.svg \
    $$PWD/qml-material/modules/Material/icons/device/signal_cellular_off.svg \
    $$PWD/qml-material/modules/Material/icons/device/battery_unknown.svg \
    $$PWD/qml-material/modules/Material/icons/device/battery_charging_90.svg \
    $$PWD/qml-material/modules/Material/icons/device/data_usage.svg \
    $$PWD/qml-material/modules/Material/icons/device/dvr.svg \
    $$PWD/qml-material/modules/Material/icons/device/battery_charging_50.svg \
    $$PWD/qml-material/modules/Material/icons/device/battery_50.svg \
    $$PWD/qml-material/modules/Material/icons/device/gps_off.svg \
    $$PWD/qml-material/modules/Material/icons/device/battery_30.svg \
    $$PWD/qml-material/modules/Material/icons/device/access_alarms.svg \
    $$PWD/qml-material/modules/Material/icons/device/developer_mode.svg \
    $$PWD/qml-material/modules/Material/icons/device/wifi_tethering.svg \
    $$PWD/qml-material/modules/Material/icons/device/battery_full.svg \
    $$PWD/qml-material/modules/Material/icons/device/screen_lock_landscape.svg \
    $$PWD/qml-material/modules/Material/icons/device/signal_wifi_off.svg \
    $$PWD/qml-material/modules/Material/icons/device/battery_charging_60.svg \
    $$PWD/qml-material/modules/Material/icons/device/brightness_medium.svg \
    $$PWD/qml-material/modules/Material/icons/device/signal_wifi_3_bar.svg \
    $$PWD/qml-material/modules/Material/icons/device/bluetooth_disabled.svg \
    $$PWD/qml-material/modules/Material/icons/device/battery_alert.svg \
    $$PWD/qml-material/modules/Material/icons/device/location_searching.svg \
    $$PWD/qml-material/modules/Material/icons/device/battery_60.svg \
    $$PWD/qml-material/modules/Material/icons/device/signal_wifi_4_bar.svg \
    $$PWD/qml-material/modules/Material/icons/device/brightness_auto.svg \
    $$PWD/qml-material/modules/Material/icons/device/gps_fixed.svg \
    $$PWD/qml-material/modules/Material/icons/device/screen_lock_portrait.svg \
    $$PWD/qml-material/modules/Material/icons/device/battery_20.svg \
    $$PWD/qml-material/modules/Material/icons/device/signal_cellular_connected_no_internet_2_bar.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_convenience_store.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_drink.svg \
    $$PWD/qml-material/modules/Material/icons/maps/hotel.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_laundry_service.svg \
    $$PWD/qml-material/modules/Material/icons/maps/traffic.svg \
    $$PWD/qml-material/modules/Material/icons/maps/layers.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_airport.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_hotel.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_hospital.svg \
    $$PWD/qml-material/modules/Material/icons/maps/beenhere.svg \
    $$PWD/qml-material/modules/Material/icons/maps/directions_car.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_grocery_store.svg \
    $$PWD/qml-material/modules/Material/icons/maps/restaurant_menu.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_pizza.svg \
    $$PWD/qml-material/modules/Material/icons/maps/satellite.svg \
    $$PWD/qml-material/modules/Material/icons/maps/store_mall_directory.svg \
    $$PWD/qml-material/modules/Material/icons/maps/pin_drop.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_gas_station.svg \
    $$PWD/qml-material/modules/Material/icons/maps/directions_subway.svg \
    $$PWD/qml-material/modules/Material/icons/maps/directions_bike.svg \
    $$PWD/qml-material/modules/Material/icons/maps/directions.svg \
    $$PWD/qml-material/modules/Material/icons/maps/navigation.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_play.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_library.svg \
    $$PWD/qml-material/modules/Material/icons/maps/rate_review.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_taxi.svg \
    $$PWD/qml-material/modules/Material/icons/maps/layers_clear.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_movies.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_restaurant.svg \
    $$PWD/qml-material/modules/Material/icons/maps/directions_bus.svg \
    $$PWD/qml-material/modules/Material/icons/maps/terrain.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_parking.svg \
    $$PWD/qml-material/modules/Material/icons/maps/map.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_bar.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_print_shop.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_phone.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_atm.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_car_wash.svg \
    $$PWD/qml-material/modules/Material/icons/maps/location_history.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_pharmacy.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_shipping.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_cafe.svg \
    $$PWD/qml-material/modules/Material/icons/maps/directions_transit.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_mall.svg \
    $$PWD/qml-material/modules/Material/icons/maps/place.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_florist.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_see.svg \
    $$PWD/qml-material/modules/Material/icons/maps/directions_walk.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_offer.svg \
    $$PWD/qml-material/modules/Material/icons/maps/flight.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_post_office.svg \
    $$PWD/qml-material/modules/Material/icons/maps/directions_ferry.svg \
    $$PWD/qml-material/modules/Material/icons/maps/my_location.svg \
    $$PWD/qml-material/modules/Material/icons/maps/local_attraction.svg \
    $$PWD/qml-material/modules/Material/icons/maps/directions_train.svg \
    $$PWD/qml-material/modules/Material/icons/social/person_add.svg \
    $$PWD/qml-material/modules/Material/icons/social/public.svg \
    $$PWD/qml-material/modules/Material/icons/social/poll.svg \
    $$PWD/qml-material/modules/Material/icons/social/notifications_none.svg \
    $$PWD/qml-material/modules/Material/icons/social/person_outline.svg \
    $$PWD/qml-material/modules/Material/icons/social/plus_one.svg \
    $$PWD/qml-material/modules/Material/icons/social/notifications_off.svg \
    $$PWD/qml-material/modules/Material/icons/social/pages.svg \
    $$PWD/qml-material/modules/Material/icons/social/domain.svg \
    $$PWD/qml-material/modules/Material/icons/social/group.svg \
    $$PWD/qml-material/modules/Material/icons/social/location_city.svg \
    $$PWD/qml-material/modules/Material/icons/social/school.svg \
    $$PWD/qml-material/modules/Material/icons/social/party_mode.svg \
    $$PWD/qml-material/modules/Material/icons/social/person.svg \
    $$PWD/qml-material/modules/Material/icons/social/notifications_on.svg \
    $$PWD/qml-material/modules/Material/icons/social/notifications_paused.svg \
    $$PWD/qml-material/modules/Material/icons/social/people.svg \
    $$PWD/qml-material/modules/Material/icons/social/notifications.svg \
    $$PWD/qml-material/modules/Material/icons/social/share.svg \
    $$PWD/qml-material/modules/Material/icons/social/group_add.svg \
    $$PWD/qml-material/modules/Material/icons/social/whatshot.svg \
    $$PWD/qml-material/modules/Material/icons/social/mood.svg \
    $$PWD/qml-material/modules/Material/icons/social/cake.svg \
    $$PWD/qml-material/modules/Material/icons/social/people_outline.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/security.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/cast.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/cast_connected.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/dock.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/keyboard_hide.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/laptop_mac.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/phonelink_off.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/tablet_mac.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/keyboard_alt.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/phonelink.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/desktop_mac.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/keyboard_tab.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/tablet.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/gamepad.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/sim_card.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/mouse.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/laptop_chromebook.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/desktop_windows.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/phone_android.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/keyboard.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/memory.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/keyboard_arrow_left.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/keyboard_arrow_right.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/laptop.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/keyboard_voice.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/keyboard_return.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/headset.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/laptop_windows.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/tablet_android.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/keyboard_capslock.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/speaker.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/keyboard_arrow_down.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/keyboard_arrow_up.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/keyboard_control.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/keyboard_backspace.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/headset_mic.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/smartphone.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/tv.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/phone_iphone.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/watch.svg \
    $$PWD/qml-material/modules/Material/icons/hardware/computer.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/expand_less.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/more_horiz.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/arrow_drop_down_circle.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/close.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/unfold_more.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/fullscreen.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/cancel.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/arrow_forward.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/arrow_back.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/unfold_less.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/arrow_drop_down.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/chevron_right.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/menu.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/arrow_drop_up.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/expand_more.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/more_vert.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/refresh.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/chevron_left.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/apps.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/check.svg \
    $$PWD/qml-material/modules/Material/icons/navigation/fullscreen_exit.svg \
    $$PWD/qml-material/modules/Material/icons/content/mail.svg \
    $$PWD/qml-material/modules/Material/icons/content/remove_circle.svg \
    $$PWD/qml-material/modules/Material/icons/content/reply.svg \
    $$PWD/qml-material/modules/Material/icons/content/select_all.svg \
    $$PWD/qml-material/modules/Material/icons/content/save.svg \
    $$PWD/qml-material/modules/Material/icons/content/remove.svg \
    $$PWD/qml-material/modules/Material/icons/content/link.svg \
    $$PWD/qml-material/modules/Material/icons/content/markunread.svg \
    $$PWD/qml-material/modules/Material/icons/content/flag.svg \
    $$PWD/qml-material/modules/Material/icons/content/forward.svg \
    $$PWD/qml-material/modules/Material/icons/content/content_paste.svg \
    $$PWD/qml-material/modules/Material/icons/content/block.svg \
    $$PWD/qml-material/modules/Material/icons/content/clear.svg \
    $$PWD/qml-material/modules/Material/icons/content/reply_all.svg \
    $$PWD/qml-material/modules/Material/icons/content/filter_list.svg \
    $$PWD/qml-material/modules/Material/icons/content/report.svg \
    $$PWD/qml-material/modules/Material/icons/content/sort.svg \
    $$PWD/qml-material/modules/Material/icons/content/backspace.svg \
    $$PWD/qml-material/modules/Material/icons/content/gesture.svg \
    $$PWD/qml-material/modules/Material/icons/content/add.svg \
    $$PWD/qml-material/modules/Material/icons/content/redo.svg \
    $$PWD/qml-material/modules/Material/icons/content/send.svg \
    $$PWD/qml-material/modules/Material/icons/content/create.svg \
    $$PWD/qml-material/modules/Material/icons/content/content_cut.svg \
    $$PWD/qml-material/modules/Material/icons/content/remove_circle_outline.svg \
    $$PWD/qml-material/modules/Material/icons/content/inbox.svg \
    $$PWD/qml-material/modules/Material/icons/content/content_copy.svg \
    $$PWD/qml-material/modules/Material/icons/content/add_box.svg \
    $$PWD/qml-material/modules/Material/icons/content/add_circle_outline.svg \
    $$PWD/qml-material/modules/Material/icons/content/undo.svg \
    $$PWD/qml-material/modules/Material/icons/content/drafts.svg \
    $$PWD/qml-material/modules/Material/icons/content/text_format.svg \
    $$PWD/qml-material/modules/Material/icons/content/add_circle.svg \
    $$PWD/qml-material/modules/Material/icons/content/archive.svg \
    $$PWD/qml-material/modules/Material/icons/communication/location_off.svg \
    $$PWD/qml-material/modules/Material/icons/communication/dnd_on.svg \
    $$PWD/qml-material/modules/Material/icons/communication/voicemail.svg \
    $$PWD/qml-material/modules/Material/icons/communication/stay_current_portrait.svg \
    $$PWD/qml-material/modules/Material/icons/communication/message.svg \
    $$PWD/qml-material/modules/Material/icons/communication/quick_contacts_mail.svg \
    $$PWD/qml-material/modules/Material/icons/communication/business.svg \
    $$PWD/qml-material/modules/Material/icons/communication/vpn_key.svg \
    $$PWD/qml-material/modules/Material/icons/communication/stay_current_landscape.svg \
    $$PWD/qml-material/modules/Material/icons/communication/phone.svg \
    $$PWD/qml-material/modules/Material/icons/communication/call_missed.svg \
    $$PWD/qml-material/modules/Material/icons/communication/dialer_sip.svg \
    $$PWD/qml-material/modules/Material/icons/communication/quick_contacts_dialer.svg \
    $$PWD/qml-material/modules/Material/icons/communication/messenger.svg \
    $$PWD/qml-material/modules/Material/icons/communication/call_merge.svg \
    $$PWD/qml-material/modules/Material/icons/communication/chat.svg \
    $$PWD/qml-material/modules/Material/icons/communication/email.svg \
    $$PWD/qml-material/modules/Material/icons/communication/portable_wifi_off.svg \
    $$PWD/qml-material/modules/Material/icons/communication/invert_colors_off.svg \
    $$PWD/qml-material/modules/Material/icons/communication/swap_calls.svg \
    $$PWD/qml-material/modules/Material/icons/communication/no_sim.svg \
    $$PWD/qml-material/modules/Material/icons/communication/clear_all.svg \
    $$PWD/qml-material/modules/Material/icons/communication/invert_colors_on.svg \
    $$PWD/qml-material/modules/Material/icons/communication/textsms.svg \
    $$PWD/qml-material/modules/Material/icons/communication/live_help.svg \
    $$PWD/qml-material/modules/Material/icons/communication/import_export.svg \
    $$PWD/qml-material/modules/Material/icons/communication/ring_volume.svg \
    $$PWD/qml-material/modules/Material/icons/communication/call_received.svg \
    $$PWD/qml-material/modules/Material/icons/communication/call_split.svg \
    $$PWD/qml-material/modules/Material/icons/communication/stay_primary_portrait.svg \
    $$PWD/qml-material/modules/Material/icons/communication/comment.svg \
    $$PWD/qml-material/modules/Material/icons/communication/location_on.svg \
    $$PWD/qml-material/modules/Material/icons/communication/call_made.svg \
    $$PWD/qml-material/modules/Material/icons/communication/call_end.svg \
    $$PWD/qml-material/modules/Material/icons/communication/stay_primary_landscape.svg \
    $$PWD/qml-material/modules/Material/icons/communication/call.svg \
    $$PWD/qml-material/modules/Material/icons/communication/forum.svg \
    $$PWD/qml-material/modules/Material/icons/communication/dialpad.svg \
    $$PWD/qml-material/modules/Material/icons/communication/contacts.svg \
    $$PWD/qml-material/modules/Material/icons/av/closed_caption.svg \
    $$PWD/qml-material/modules/Material/icons/av/mic_off.svg \
    $$PWD/qml-material/modules/Material/icons/av/stop.svg \
    $$PWD/qml-material/modules/Material/icons/av/volume_mute.svg \
    $$PWD/qml-material/modules/Material/icons/av/my_library_books.svg \
    $$PWD/qml-material/modules/Material/icons/av/pause_circle_outline.svg \
    $$PWD/qml-material/modules/Material/icons/av/playlist_add.svg \
    $$PWD/qml-material/modules/Material/icons/av/movie.svg \
    $$PWD/qml-material/modules/Material/icons/av/fast_rewind.svg \
    $$PWD/qml-material/modules/Material/icons/av/pause.svg \
    $$PWD/qml-material/modules/Material/icons/av/subtitles.svg \
    $$PWD/qml-material/modules/Material/icons/av/video_collection.svg \
    $$PWD/qml-material/modules/Material/icons/av/hearing.svg \
    $$PWD/qml-material/modules/Material/icons/av/not_interested.svg \
    $$PWD/qml-material/modules/Material/icons/av/games.svg \
    $$PWD/qml-material/modules/Material/icons/av/high_quality.svg \
    $$PWD/qml-material/modules/Material/icons/av/loop.svg \
    $$PWD/qml-material/modules/Material/icons/av/explicit.svg \
    $$PWD/qml-material/modules/Material/icons/av/my_library_music.svg \
    $$PWD/qml-material/modules/Material/icons/av/av_timer.svg \
    $$PWD/qml-material/modules/Material/icons/av/queue.svg \
    $$PWD/qml-material/modules/Material/icons/av/album.svg \
    $$PWD/qml-material/modules/Material/icons/av/skip_previous.svg \
    $$PWD/qml-material/modules/Material/icons/av/mic_none.svg \
    $$PWD/qml-material/modules/Material/icons/av/new_releases.svg \
    $$PWD/qml-material/modules/Material/icons/av/skip_next.svg \
    $$PWD/qml-material/modules/Material/icons/av/volume_off.svg \
    $$PWD/qml-material/modules/Material/icons/av/pause_circle_fill.svg \
    $$PWD/qml-material/modules/Material/icons/av/replay.svg \
    $$PWD/qml-material/modules/Material/icons/av/mic.svg \
    $$PWD/qml-material/modules/Material/icons/av/shuffle.svg \
    $$PWD/qml-material/modules/Material/icons/av/play_arrow.svg \
    $$PWD/qml-material/modules/Material/icons/av/recent_actors.svg \
    $$PWD/qml-material/modules/Material/icons/av/equalizer.svg \
    $$PWD/qml-material/modules/Material/icons/av/repeat_one.svg \
    $$PWD/qml-material/modules/Material/icons/av/play_circle_outline.svg \
    $$PWD/qml-material/modules/Material/icons/av/repeat.svg \
    $$PWD/qml-material/modules/Material/icons/av/videocam.svg \
    $$PWD/qml-material/modules/Material/icons/av/surround_sound.svg \
    $$PWD/qml-material/modules/Material/icons/av/videocam_off.svg \
    $$PWD/qml-material/modules/Material/icons/av/web.svg \
    $$PWD/qml-material/modules/Material/icons/av/play_shopping_bag.svg \
    $$PWD/qml-material/modules/Material/icons/av/snooze.svg \
    $$PWD/qml-material/modules/Material/icons/av/fast_forward.svg \
    $$PWD/qml-material/modules/Material/icons/av/volume_up.svg \
    $$PWD/qml-material/modules/Material/icons/av/my_library_add.svg \
    $$PWD/qml-material/modules/Material/icons/av/volume_down.svg \
    $$PWD/qml-material/modules/Material/icons/av/radio.svg \
    $$PWD/qml-material/modules/Material/icons/av/play_circle_fill.svg \
    $$PWD/qml-material/modules/Material/icons/av/queue_music.svg \
    $$PWD/qml-material/modules/Material/icons/main.sh \
    $$PWD/qml-material/modules/Material/IconButton.qml
